### ISSUE TITLE
Update flatpak platform to 6

### ISSUE THREAD

**Issue by danirabbit** [Lafydev/Animage#10]
Hey there!

I'm working right now on manually uploading apps while we're finishing up the new dashboard. It looks like your app is ready to go, except that it's still using the `daily` version of the flatpak platform instead of the stable version `6`. As soon as that is updated, I would love to get Animage published :)

**Comment by Lafydev** [comment]
Thank you !

**Comment by danirabbit** [comment]
Awesome! Just need a point release and I'll set up the import!
