### ISSUE TITLE
Flatpak build failed due to appdata

### ISSUE THREAD

**Issue by danirabbit** [Lafydev/Animage#11]
Hey there! Looks like we were unable to build your app in Flatpak because of an error in appdata: https://github.com/elementary/appcenter-reviews/pull/47/checks?check_run_id=3243760631#step:4:106

You can check the validation of your appdata file by running `appstream-util validate com.github.lafydev.animage.appdata.xml` on the version of your appdata that is generated after building

It looks like the issue is largely the mixed tabs and spaces in your appdata file.

You might want to consider adding a CI workflow to your repo that builds Flatpak: https://docs.elementary.io/develop/writing-apps/our-first-app/continuous-integration

**Comment by Lafydev** [comment]
ok thank you
